version: 1.0.0
name: architecto
description: "Architecto is a mobile app designed to manage labor attendance, track site stock, and maintain essential details for construction projects."

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  adaptive_theme: ^3.6.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  provider: ^6.1.2
  animate_do: ^3.3.4
  lottie: ^3.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: "Sriracha"
      fonts:
        - asset: fonts/sriracha/Sriracha-Regular.ttf
